version: '3.8'
services:
  red-bot:
    image: rhomelab/labbot:latest
    container_name: RedBot
    restart: always
    command: /bin/bash -c "redbot MyBotName --team-members-are-owners --rpc --rpc-port 6133"
    ports: [42356:42356]
    volumes:
      - /opt/RedBot/share:/home/redbot/.local/share
      - /opt/RedBot/Red-DiscordBot:/usr/local/share/Red-DiscordBot

  red-dash:
    image: tigattack/red-dashboard:latest
    container_name: RedBot_Dashboard
    restart: always
    network_mode: "container:RedBot"
    depends_on: ["redbot"]
    environment:
      WEB_PORT: 42356
      RPC_PORT: 6133
