version: '3.8'
services:
  red-bot:
    image: rhomelab/red-discordbot:latest
    container_name: RedBot
    restart: always
    ports: [42356:42356]
    environment:
      INSTANCE_NAME: "RedBot"
      PREFIX: "^"
      TOKEN: "yourBotToken"
      RPC_ENABLED: "true"
      # RPC_PORT: "CUSTOM_RPC_PORT" # Optional, default 6133
    volumes:
      - /opt/RedBot/data:/redbot/data

  red-dash:
    image: tigattack/red-dashboard:latest
    container_name: RedBot_Dashboard
    restart: always
    network_mode: "container:RedBot"
    depends_on: ["red-bot"]
    environment:
      WEB_PORT: 42356
      RPC_PORT: 6133
